// <auto-generated />
namespace eCommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v54_edit_entidad_financiera : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v54_edit_entidad_financiera));
        
        string IMigrationMetadata.Id
        {
            get { return "202204141813555_v5.4_edit_entidad_financiera"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
