// <auto-generated />
namespace eCommerce.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v8_tipoCambio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v8_tipoCambio));
        
        string IMigrationMetadata.Id
        {
            get { return "202206030510442_v8_tipoCambio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
